name: FromManyOne
favicon: null
layout_spectrum: 0.19386
typography_spectrum: 0.49591
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080b10'
    - '#ffffff'
    - '#baada4'
    - '#3e424b'
    - '#8a7059'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
