name: FromManyOne
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49591
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080b10'
    - '#ffffff'
    - '#baada4'
    - '#3e424b'
    - '#8a7059'
  brandStrength: 0.8327033000532538
  lightness: 0.0125448
  saturation: 0.234767
  rhythmicContrast: 0.7114695
purpose: []
