favicon: null
name: FromManyOne
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3996416
  brandStrength: 0.7078853
  lightness: 0
  brandColors:
    - '#010100'
    - '#A29992'
    - '#146762'
    - '#FFFFFF'
    - '#F49A00'
  rhythmicContrast: 0.7114695
typography_spectrum: 0.49591
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
